src/music-links-converter/default/objects/MusicServiceSetting__mdt/MusicServiceSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores the MusicLinksConverter bot settings</description>
    <label>Music Links Converter Bot Setting</label>
    <pluralLabel>Music Links Converter Bot Settings</pluralLabel>
</CustomObject>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>The name of the Apex class that implement the music service API</description>
    <inlineHelpText>The name of the Apex class that implement the music service API</inlineHelpText>
    <label>Service</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/ShareLinkUrl__c.field-meta.xml
<CustomField>
    <fullName>ShareLinkUrl__c</fullName>
    <description>The domain URL for the music service share link</description>
    <inlineHelpText>The domain URL for the music service share link</inlineHelpText>
    <label>Share Link Url</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/TrackRecognizer__c.field-meta.xml
<CustomField>
    <fullName>TrackRecognizer__c</fullName>
    <description>The name of the Apex class that implements recognition of a track by an URL</description>
    <inlineHelpText>The name of the Apex class that implements recognition of a track by an URL</inlineHelpText>
    <label>Track Recognizer</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/music-links-converter/default/classes/MusicLinksConverterBotServiceFactory.cls
public class MusicLinksConverterBotServiceFactory {
    public MusicService createMusicServiceService(MusicServiceType type) {
        return (MusicService) BotUtils.createInstance(MusicServiceSettingsProvider.get(type).Service__c);
    }

    public ITrackRecognizer createTrackRecognizer(String trackUrl) {
        for (MusicServiceSetting__mdt settings : MusicServiceSettingsProvider.getAll()) {
            if (trackUrl.startsWith(settings.ShareLinkUrl__c)) {
                return (ITrackRecognizer) BotUtils.createInstance(settings.TrackRecognizer__c);
            }
        }
        throw new ImplementationNotFoundException(
            'Track Recognizer implementation was not found',
            new BotJsonPayload().set('trackUrl', trackUrl)
        );
    }

    public class ImplementationNotFoundException extends BotCustomException {
        public ImplementationNotFoundException(String message, BotJsonPayload payload) {
            super(message, payload);
        }
    }
}