src/music-links-converter/default/objects/MusicServiceSetting__mdt/MusicServiceSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores the MusicLinksConverter bot settings</description>
    <label>Music Links Converter Bot Setting</label>
    <pluralLabel>Music Links Converter Bot Settings</pluralLabel>
</CustomObject>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <description>The music service base API endpoint</description>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/AuthorizationApiUrl__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationApiUrl__c</fullName>
    <description>The music service authorization API endpoint</description>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>The name of the Apex class that implement the music service API</description>
    <inlineHelpText>The name of the Apex class that implement the music service API</inlineHelpText>
    <label>Service</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/ShareLinkUrl__c.field-meta.xml
<CustomField>
    <fullName>ShareLinkUrl__c</fullName>
    <description>The domain URL for the music service share link</description>
    <inlineHelpText>The domain URL for the music service share link</inlineHelpText>
    <label>Share Link Url</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/music-links-converter/default/objects/MusicServiceSetting__mdt/fields/TrackRecognizer__c.field-meta.xml
<CustomField>
    <fullName>TrackRecognizer__c</fullName>
    <description>The name of the Apex class that implements recognition of a track by an URL</description>
    <inlineHelpText>The name of the Apex class that implements recognition of a track by an URL</inlineHelpText>
    <label>Track Recognizer</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/music-links-converter/default/classes/MusicServiceSettingsProvider.cls
public class MusicServiceSettingsProvider {
    private static final Integer SETTING_QUERY_LIMIT = 50;

    private static final Map<MusicServiceType, MusicServiceSetting__mdt> settings = new Map<MusicServiceType, MusicServiceSetting__mdt>();

    private MusicServiceSettingsProvider() {}

    static {
        initSettings();
    }

    public static MusicServiceSetting__mdt get(MusicServiceType type) {
        if (!settings.containsKey(type)) {
            throw new IllegalArgumentException('No setting exists for the ' + type + ' music service type');
        }
        return settings.get(type);
    }

    public static List<MusicServiceSetting__mdt> getAll() {
        return settings.values();
    }

    private static void initSettings() {
        List<MusicServiceSetting__mdt> allSettings = [
            SELECT DeveloperName, ApiUrl__c, AuthorizationApiUrl__c, ShareLinkUrl__c, Service__c, TrackRecognizer__c
            FROM MusicServiceSetting__mdt
            LIMIT :SETTING_QUERY_LIMIT
        ];
        for (MusicServiceSetting__mdt setting : allSettings) {
            settings.put(MusicServiceType.valueOf(setting.DeveloperName), setting);
        }
    }
}